### ISSUE TITLE
Wagtail wishlist: Video embed bug in Wagtail Rich Text Editor (Wagtail 1.0 and 2.0)

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2212]
**What we are after:**
Responsive embedded videos in the Wagtail Rich Text Editor, that do not have extraneous padding-bottom.

Currently, the video embed option inside the Wagtail Rich Text Editor (for both Wagtail 1.X and 2.0) adds padding under the video and does not render responsively in browsers.

In order to make the video responsive, Wagtail  automatically determines the aspect ratio of the video and then wraps it in a containing div with a padding-bottom equal to the percentage of width to height of the video. So a YouTube video with a 16:9 aspect ratio gets wrapped in a div with 56.25% padding-bottom. (9 is 56.25 percent of 16)

The  'bug' is that, in order to fully achieve this technique, the iframe being embedded must be absolutely positioned within the containing element and have a width/height of 100%. Wagtail does not automatically add this.

It turns out that some older  Wagtail docs point out the need to add some CSS to fully achieve this effect:
http://docs.wagtail.io/en/v1.13.1/topics/writing_templates.html#responsive-embeds

We need to add CSS to target the `responsive-object` class and its child `iframe` (or other media element) to absolutely position the iframe and give it a 100% width and height.

Related work: 
https://github.com/fecgov/fecnet/issues/189

This issue needs a bit of  grooming as we need to see if Wagtail content editors are OK with embedded videos (in the RTE) to be 100% width because that is required for this technique to work.

**Comment by apburnes** [comment]
@patphongs and I were testing a different Wagtail editor issue and came up with this...

```scss
.responsive-object {
	width: 100% !important;
	height: auto !important;
	padding: 0 !important;

	iframe {
		width: 100% !important;
	}
}
```

**Comment by johnnyporkchops** [comment]
The SCSS above did not work for me locally. The video height does not show all the video. I think the solution is not just to figure out how to remove he padding under the video, but to add the missing SCSS to complete the responsive technique. But maybe I am missing something about how the SCSS in the previous comment is supposed to work.

The extra padding is a symptom of the fact that the default CSS added to ensure the intrinsic aspect ratio is not complete.
Here is what works for me: 
```SCSS
.responsive-object {
    position: relative;


 iframe, object, embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
 }
}
```
And to address my grooming concern above --I think we can accept the video being 100% width inside the text areas,
