### ISSUE TITLE
update config.yml with correct python and postgres

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#3929]
### Summary
issue https://github.com/fecgov/fec-cms/issues/3757 was to upgrade local env for pg 11 and update documentation. `config.yml` needs to be updated as well:

- [ ] python version
- [ ] postgres version

```
      - image: circleci/python:3.7.4-stretch-node-browsers
        environment:
          TZ: America/New_York
          DATABASE_URL: postgres://postgres@0.0.0.0/cfdm_cms_test

      # PostgreSQL
      - image: circleci/postgres:9.6.8
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: cfdm_cms_test
```
